/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esqueleto;

import Login.Login_principal;
import Vistas_de_Administracion.AdministrarCliente;
import Vistas_de_Administracion.AdministrarEmpleado;
import Vistas_de_Administracion.AdministrarProducto;
import Vistas_de_Administracion.AdministrarProveedores;
import javax.swing.JOptionPane;

/**
 *
 * @author LUCAS
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1_Admin_producto = new javax.swing.JButton();
        jButton2_Admin_proveedor = new javax.swing.JButton();
        jButton3_Admin_empleado = new javax.swing.JButton();
        jButton5_salir = new javax.swing.JButton();
        jButton4_Admin_cliente1 = new javax.swing.JButton();
        jButton5_salir1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1_Admin_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamaño_de_34/caja.png"))); // NOI18N
        jButton1_Admin_producto.setText("Admin_producto");
        jButton1_Admin_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Admin_productoActionPerformed(evt);
            }
        });

        jButton2_Admin_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamaño_de_34/entrega.png"))); // NOI18N
        jButton2_Admin_proveedor.setText("Admin_proveedores");
        jButton2_Admin_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Admin_proveedorActionPerformed(evt);
            }
        });

        jButton3_Admin_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamaño_de_34/hombre.png"))); // NOI18N
        jButton3_Admin_empleado.setText("Admin_empleado");
        jButton3_Admin_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_Admin_empleadoActionPerformed(evt);
            }
        });

        jButton5_salir.setText("Salir");
        jButton5_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_salirActionPerformed(evt);
            }
        });

        jButton4_Admin_cliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tamaño_de_34/pareja.png"))); // NOI18N
        jButton4_Admin_cliente1.setText("Admin_cliente");
        jButton4_Admin_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_Admin_cliente1ActionPerformed(evt);
            }
        });

        jButton5_salir1.setText("Cerrar sesion");
        jButton5_salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_salir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4_Admin_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2_Admin_proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton3_Admin_empleado)
                .addGap(18, 18, 18)
                .addComponent(jButton1_Admin_producto)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButton5_salir1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(jButton5_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4_Admin_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_Admin_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_Admin_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1_Admin_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5_salir)
                    .addComponent(jButton5_salir1))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_Admin_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Admin_proveedorActionPerformed
     AdministrarProveedores ad3 = new AdministrarProveedores();
       ad3.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton2_Admin_proveedorActionPerformed

    private void jButton3_Admin_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_Admin_empleadoActionPerformed
     AdministrarEmpleado ad1= new AdministrarEmpleado();
                  ad1.setVisible(true);
           this.dispose();

    }//GEN-LAST:event_jButton3_Admin_empleadoActionPerformed

    private void jButton1_Admin_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Admin_productoActionPerformed
    AdministrarProducto ad2= new AdministrarProducto();
               ad2.setVisible(true);
                this.dispose();

    }//GEN-LAST:event_jButton1_Admin_productoActionPerformed

    private void jButton4_Admin_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_Admin_cliente1ActionPerformed
     AdministrarCliente ad =new AdministrarCliente();
           ad.setVisible(true);
           this.dispose();


    }//GEN-LAST:event_jButton4_Admin_cliente1ActionPerformed

    private void jButton5_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_salirActionPerformed

            int a;
            a=JOptionPane.showConfirmDialog(null,"Desea Salir"," ***Aviso***",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null," Nos vemos ");
       System.exit(0);  
        }
    }//GEN-LAST:event_jButton5_salirActionPerformed

    private void jButton5_salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_salir1ActionPerformed
       Login_principal l = new Login_principal();
        l.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton5_salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Admin_producto;
    private javax.swing.JButton jButton2_Admin_proveedor;
    private javax.swing.JButton jButton3_Admin_empleado;
    private javax.swing.JButton jButton4_Admin_cliente1;
    private javax.swing.JButton jButton5_salir;
    private javax.swing.JButton jButton5_salir1;
    // End of variables declaration//GEN-END:variables
}
