/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas_de_Administracion;

import Vistas_de_Administracion.Actualizacion_de_datos.ActualizarEmpleado;
import Controlador.ControladorGeneral;
import Conexion.BaseDatos;
import Conexion.DBSetencias;
import Controlador.C_G_Empleado;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import Utilidades.ControladorPantalla;
import Vistas_de_Administracion.cargas_de_datos.CargaEmpleado;
import esqueleto.Menu;

/**
 *
 * @author daisi
 */
public class AdministrarEmpleado extends javax.swing.JFrame {
    
     public static String Searchs;
     C_G_Empleado gg;
     DefaultTableModel modelo;
     //private ControladorPantalla refcontroladorPantalla;
   
    
    
    /**
     * Creates new form AdministrarEmpleado
     */
    public AdministrarEmpleado() {
        initComponents();
        setLocationRelativeTo(this);
        gg = new C_G_Empleado();
        modelo = new DefaultTableModel();
        actualizarTabla(DBSetencias.ConsultaSelectEmpleado);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(233, 132, 31));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "DNI", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setColumnSelectionAllowed(true);
        tabla.setName("tabla"); // NOI18N
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);
        tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel7.setText("Empleado :");

        txt_search.setToolTipText("Comience a escribir para buscar");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jButton6.setText("Mostrar Todos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificar");
        jButton3.setAlignmentY(0.0F);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Empleado");

        jButton5_menu.setText("Menu");
        jButton5_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jButton5_menu))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jButton5_menu)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CargaEmpleado Cp = new CargaEmpleado();
        Cp.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           // TODO add your handling code here:
          if(!tabla.getSelectionModel().isSelectionEmpty()){
          int row = tabla.getSelectedRow();
          int id = (int) (tabla.getModel().getValueAt(row, 0)) ; 
          String Nombre = (tabla.getModel().getValueAt(row, 1).toString()) ; 
          String Descripcion = (tabla.getModel().getValueAt(row, 2).toString()) ; 
          int Precio = (int) (tabla.getModel().getValueAt(row, 3)) ; 
          int Stock = (int) (tabla.getModel().getValueAt(row, 4)) ; 
          ActualizarEmpleado Ap = new ActualizarEmpleado();
          Ap.ObtenerInfo(id,Nombre,Descripcion,Precio,Stock);
          Ap.setVisible(true);
          }else{
               JOptionPane.showMessageDialog(null, "Para modificar un Empleado seleccione uno de la lista"); 
         
          }
           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        //String query = txt_search.getText();
        //Filter(query);
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!tabla.getSelectionModel().isSelectionEmpty()){
        int row = tabla.getSelectedRow();
        int Onclick = (int) (tabla.getModel().getValueAt(row, 0)) ; 
        String ProductoNombre = (tabla.getModel().getValueAt(row, 1).toString()) ; 
        int reply = JOptionPane.showConfirmDialog(null, "Realmente desea eliminar el Empleado ID " + Onclick +" - "+ProductoNombre+" ?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (reply == JOptionPane.YES_OPTION) {
            gg.EliminarEmpleado(Onclick);
            JOptionPane.showMessageDialog(null, "El Empleado fue eliminado correctamente");
            LimpiarTabla();
            actualizarTabla(DBSetencias.ConsultaSelectEmpleado);
          
        }else {
           JOptionPane.showMessageDialog(null, "Se cancelo la operacion para eliminar el Empleado");
        }
         }else{
               JOptionPane.showMessageDialog(null, "Para eliminar un Empleado seleccione uno de la lista"); 
         
          }
         
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        actualizarTabla(DBSetencias.ConsultaSelectEmpleado);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        
        try{
        int row = tabla.getSelectedRow();
        String Onclick = (tabla.getModel().getValueAt(row, 0).toString()) ;   
        System.out.println(Onclick);
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
        }
            
        
        
        
        
        
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        String Busqueda = txt_search.getText();
        gg.BuscarEmpleado(Busqueda,tabla); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_menuActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton5_menuActionPerformed
   
    public void LimpiarTabla(){
         int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
          modelo.removeRow(i);
          }
        actualizarTabla(DBSetencias.ConsultaSelectEmpleado);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        AdministrarEmpleado form = new AdministrarEmpleado();
        form.setVisible(true);
  }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5_menu;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

private void actualizarTabla(String consulta) {
        modelo = gg.mostrar(consulta);
        tabla.setModel(modelo);
        //Enable to hide "ID" - Disable to show "ID//
        //tabla.getColumnModel().removeColumn(tabla.getColumnModel().getColumn(0));
    }
    

        private void  Filter(String Query){
            // No se esta utilizando
        TableRowSorter<DefaultTableModel>  tr = new TableRowSorter<DefaultTableModel>(modelo);
        tabla.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(Query));
    }




}
